packages:
  - "apps/price_pusher"
  - "apps/hermes/client/js"
  - "governance/xc_admin/packages/*"
  - "governance/multisig_wh_message_builder"
  - "price_service/sdk/js"
  - "price_service/client/js"
  - "pythnet/message_buffer"
  - "target_chains/solana/sdk/js/solana_utils"
  - "target_chains/solana/sdk/js/pyth_solana_receiver"