[workspace]
members = [
    "programs/pyth-push-oracle",
    "programs/pyth-solana-receiver",
]

[features]
seeds = false
skip-lint = false

[programs.devnet]
pyth_solana_receiver = "G6EoTTTgpkNBtVXo96EQp2m6uwwVh2Kt6YidjkmQqoha"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
export = "anchor build && ./scripts/patch_idl.sh"
