name: JS/TS checks
on:
  pull_request:
    paths:
      - "**.tsx?"
      - "**.jsx?"
      - "**.json"
      - "**.sol"
      - "**/package.json"
      - "**/package-lock.json"
      - "**/tsconfig.json"
  push:
    branches: [main]
    paths:
      - "**.tsx?"
      - "**.jsx?"
      - "**.json"
      - "**.sol"
      - "**/package.json"
      - "**/package-lock.json"
      - "**/tsconfig.json"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
<<<<<<< HEAD:.github/workflows/ci-typescript.yml
          node-version: 18
=======
          node-version-file: "package.json"
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.81.0
      - name: Install Solana Cli
        run: |
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
      - name: Set Solana Cli version
        run: agave-install init 1.18.26
      - name: Create Solana key
        run: solana-keygen new --no-bip39-passphrase
      - name: Install Anchor
        run: RUSTFLAGS= cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.1 anchor-cli
>>>>>>> 44d691a9 (chore: add missing package name and remove lock files (#2128)):.github/workflows/ci-turbo-test.yml
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: "args: [--frozen-lockfile]"
      - name: Build
        run: pnpm exec lerna run build
      - name: Test
        run: pnpm exec lerna run test
      - name: Lint
        run: pnpm exec lerna run lint
      - name: Generate ABIs
        run: pnpm exec lerna run generate-abi
      - name: Check ABIs
        run: pnpm exec lerna run check-abi
